// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lab3.Infrastructure.Data;

#nullable disable

namespace lab3.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260524194444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lab3.Domain.Entities.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("FeelsLikeC")
                        .HasColumnType("double precision");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("TempC")
                        .HasColumnType("double precision");

                    b.Property<int?>("WindDataId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WindDataId")
                        .IsUnique();

                    b.ToTable("weather_records", (string)null);
                });

            modelBuilder.Entity("lab3.Domain.Entities.WindData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("GustKph")
                        .HasColumnType("double precision");

                    b.Property<double>("GustMph")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsGoodToGoOutside")
                        .HasColumnType("boolean");

                    b.Property<string>("Sunrise")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Sunset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("WindDegree")
                        .HasColumnType("integer");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("WindKph")
                        .HasColumnType("double precision");

                    b.Property<double>("WindMph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("wind_data", (string)null);
                });

            modelBuilder.Entity("lab3.Domain.Entities.WeatherRecord", b =>
                {
                    b.HasOne("lab3.Domain.Entities.WindData", "WindData")
                        .WithOne("WeatherRecord")
                        .HasForeignKey("lab3.Domain.Entities.WeatherRecord", "WindDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WindData");
                });

            modelBuilder.Entity("lab3.Domain.Entities.WindData", b =>
                {
                    b.Navigation("WeatherRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
